### ISSUE TITLE
Activate GitHub Pages

### ISSUE THREAD

**Issue by ratnanil** [windijon/ZHAW-Patterns-Trends-Semester_Project#1]
Hi there! 

I see that you are working on your semester project 😄 

I've noticed that you haven't yet activated GitHub Pages on your repo. Can you do this? All you need to do is go to the settings of your repo, go the tab "Pages" and activate GitHub Pages by choosing your branch (`main` or `master`) and then the folder `root` (see screenshot below). The green box will appear if you click on save.

If you have any questions, please book a session with me via https://calendly.com/rata-zhaw/

![gh-pages](https://raw.githubusercontent.com/ComputationalMovementAnalysis/Slides/master/images/gh-pages-2.png)

**Comment by ratnanil** [comment]
I think you can close this issue

**Comment by windijon** [comment]
close
