### ISSUE TITLE
tabes in your report

### ISSUE THREAD

**Issue by ratnanil** [windijon/ZHAW-Patterns-Trends-Semester_Project#4]
https://github.com/windijon/ZHAW-Patterns-Trends-Semester_Project/blob/444a7fd87440d59a96090f0f199cc0f3a45466b6/Semesterproject.Rmd#L515-L533

I don't think it's reasonable to show the same data twice (once as a boxplot, once as a table). But if you do want to create a table, pipe your tibble into a `knitr::kabel()`, e.g.:

```diff
 ws_newyear_speed %>% 
   group_by(TierName) %>% 
   subset(select=-c(E,N)) %>% 
-   summarise(mean = mean(speed, na.rm =TRUE))
+   summarise(mean = mean(speed, na.rm =TRUE)) %>%
+   knitr::kabel()
```

**Comment by windijon** [comment]
done
